<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQBqqxNK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQBqqxNK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQBqqxNK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQBqqxNK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQBqqxNK\App_KernelDevDebugContainer([
    'container.build_hash' => 'QBqqxNK',
    'container.build_id' => '737eeeac',
    'container.build_time' => 1690984773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQBqqxNK');
