<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6tF1iD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6tF1iD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6tF1iD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6tF1iD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6tF1iD\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6tF1iD',
    'container.build_id' => 'a9e92b67',
    'container.build_time' => 1690925818,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6tF1iD');
