<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2bEpxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2bEpxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2bEpxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2bEpxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2bEpxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2bEpxC',
    'container.build_id' => '448fe0aa',
    'container.build_time' => 1690857976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2bEpxC');
